// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbhoycmtvdgslaagwcfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiaG95Y210dmRnc2xhYWd3Y2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTg2NzAsImV4cCI6MjA1NjEzNDY3MH0.jygFV9SCiQlra-lo4Y7uLi5FsVBzA_hkZEsYRcDoQcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);